// Autogenerated CPP file

#include <QString>
#include "Version.h"

QString Version::GetVersionString()
{
  return QString("2.2.1.dev-fa3976af");
}

QString Version::GetCanonicalVersionString()
{
  return QString("2.2.1-fa3976af");
}

QString Version::GetBuildDate()
{
  return QString("2018-01-13");
}

QString Version::GetWebVersion()
{
  return QString("");
}

QString Version::GetDependenciesVersion()
{
  return QString("");
}

QString Version::GetQtDepsVersion()
{
  return QString("");
}
